$background = rgb(0a0a0a)
$foreground = rgb(e8e8e8)
$shadow_color = rgba(0a0a0acc)
$shadow_color_inactive = rgba(0a0a0a99)
$color0 = rgb(111111)
$color1 = rgb(222222)
$color2 = rgb(333333)
$color3 = rgb(444444)
$color4 = rgb(666666)
$color5 = rgb(888888)
$color6 = rgb(aaaaaa)
$color7 = rgb(cccccc)
$color8 = rgb(555555)
$color9 = rgb(777777)
$color10 = rgb(999999)
$color11 = rgb(bbbbbb)
$color12 = rgb(dddddd)
$color13 = rgb(eeeeee)
$color14 = rgb(f0f0f0)
$color15 = rgb(ffffff)
