# Shanmukha Kumar Karra — minimal autostart

exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
exec-once = systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP

exec-once = bash $scriptsDir/PortalHyprland.sh
exec-once = bash $scriptsDir/Polkit.sh
exec-once = nm-applet --indicator
exec-once = bash $UserScripts/hyprmaster-ui.sh
exec-once = wl-paste --type text --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store
exec-once = hypridle
exec-once = $HOME/.config/hypr/initial-boot.sh
