# Script paths
$scriptsDir = $HOME/.config/hypr/scripts
$UserScripts = $HOME/.config/hypr/UserScripts


# Terminal layouts on startup (corrected)

# Left top terminal: htop (80% height)
exec-once = sh -c "kitty --class HTop -e htop; sleep 0.5; hyprctl dispatch move workspace 1 windowclass HTop to 0 0 50 80"

# Left bottom terminal: cmatrix (20% remaining)
exec-once = sh -c "kitty --class CMatrix -e cmatrix; sleep 0.5; hyprctl dispatch move workspace 1 windowclass CMatrix to 0 80 50 20"

# Right bottom terminal: normal kitty (60% height)
exec-once = sh -c "kitty --class RightTerm; sleep 0.5; hyprctl dispatch move workspace 1 windowclass RightTerm to 50 40 50 60"

# Right top split: cava and tty-clock (each 20% height)
exec-once = sh -c "kitty --class Cava -e cava; sleep 0.5; hyprctl dispatch move workspace 1 windowclass Cava to 50 0 50 20"

exec-once = sh -c "kitty --class TTYClock -e tty-clock; sleep 0.5; hyprctl dispatch move workspace 1 windowclass TTYClock to 50 20 50 20"



$wallDIR = /home/shannu24/Downloads/Wallpapers
$lock = $scriptsDir/LockScreen.sh

# Start wallpaper daemon
exec-once = swww query || swww-daemon

# Set random wallpaper + wallust colors
exec-once = ~/.config/hypr/scripts/WallpaperRandom.sh


exec-once = ~/.config/hypr/scripts/launch_dashboard.sh

# Network applet
exec-once = nm-applet --indicator


# Auto theme
exec-once = ~/.config/hypr/UserScripts/autotheme.sh


# Environment
exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
exec-once = systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
exec-once = iio-hyprland


# Polkit
exec-once = $scriptsDir/Polkit.sh


# UI apps
exec-once = waybar
exec-once = swaync


# Clipboard manager
exec-once = wl-paste --type text --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store


# Borders & utilities
exec-once = $UserScripts/RainbowBorders.sh
exec-once = hypridle
exec-once = pypr


# Plugins reload
exec-once = hyprpm reload -n

