# Shanmukha Kumar Karra — noir-minimal (flat, low blur)

general {
    col.active_border = $color12 $color10 45deg
    col.inactive_border = rgba(d3c6aa22)
}

decoration {
    rounding = 10
    active_opacity = 0.92
    inactive_opacity = 0.85
    blur {
        enabled = true
        size = 6
        passes = 2
    }
    shadow {
        enabled = true
        range = 18
        render_power = 2
        color = rgba(00000055)
    }
}
