# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #
# /* wallust template - colors-kitty */

foreground         #E1EAF2
background         #141516
cursor             #7A8189

active_tab_foreground     #141516
active_tab_background     #E1EAF2
inactive_tab_foreground   #E1EAF2
inactive_tab_background   #141516

active_border_color   #E1EAF2
inactive_border_color #141516
bell_border_color     #484D52

color0      #3E3F41
color1		#484D52
color2		#484D52
color3		#586A7F
color4		#64849E
color5		#64849E
color6		#A8C2DA
color7		#CBD8E4
color8		#8E97A0
color9		#484D52
color10		#484D52
color11		#586A7F
color12		#64849E
color13		#64849E
color14		#A8C2DA
color15		#CBD8E4