$background = rgb(2d353b)
$foreground = rgb(d3c6aa)
$shadow_color = rgba(2d353bcc)
$shadow_color_inactive = rgba(2d353b99)
$color0 = rgb(343f44)
$color1 = rgb(e67e80)
$color2 = rgb(a7c080)
$color3 = rgb(dbbc7f)
$color4 = rgb(7fbbb3)
$color5 = rgb(d699b6)
$color6 = rgb(83c092)
$color7 = rgb(859289)
$color8 = rgb(4f585e)
$color9 = rgb(e67e80)
$color10 = rgb(a7c080)
$color11 = rgb(dbbc7f)
$color12 = rgb(7fbbb3)
$color13 = rgb(d699b6)
$color14 = rgb(83c092)
$color15 = rgb(d3c6aa)
