# Shanmukha Kumar Karra — matugen kitty
background #{{colors.background.default.hex_stripped}}
foreground #{{colors.on_background.default.hex_stripped}}
cursor #{{colors.primary.default.hex_stripped}}
